//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealtCard
    {
        public int RecordID { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string Description { get; set; }
        public string DateOfRecord { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
