//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CuratorsEntities : DbContext
    {
        public static CuratorsEntities db;

        public CuratorsEntities()
            : base("name=CuratorsEntities")
        {
        }

        public static CuratorsEntities GetContext()
        {
			if (db == null)
			{
				db = new CuratorsEntities();
			}

			return db;
		}
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Curator> Curator { get; set; }
        public virtual DbSet<HealtCard> HealtCard { get; set; }
        public virtual DbSet<Parent> Parent { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Student_Parent_Relationship> Student_Parent_Relationship { get; set; }
        public virtual DbSet<SummaryLedger> SummaryLedger { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
    }
}
