//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Health_Card
    {
        public int Record_ID { get; set; }
        public Nullable<int> Student_ID { get; set; }
        public string Record_Description { get; set; }
        public Nullable<System.DateTime> Date_of_Record { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
