//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int event_id { get; set; }
        public string event_title { get; set; }
        public string kind_of_event { get; set; }
        public string event_date { get; set; }
        public string event_time { get; set; }
    }
}
