//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timetable
    {
        public int class_id { get; set; }
        public Nullable<int> group_number { get; set; }
        public Nullable<int> subject_id { get; set; }
        public string time_timetable { get; set; }
        public Nullable<int> audience { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
