//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class trizbd_bdEntities1 : DbContext
    {
        private static trizbd_bdEntities1 _context;
        public trizbd_bdEntities1()
            : base("name=trizbd_bdEntities1")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public static trizbd_bdEntities1 GetContext()
        {
            if (_context == null) _context = new trizbd_bdEntities1();
            return _context;
        }

        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Groups> Group { get; set; }
        public virtual DbSet<Instructor> Instructors { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<Timetable> Timetables { get; set; }
    }
}
