//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Statement_curatorEntities : DbContext
    {
        public Statement_curatorEntities()
            : base("name=Statement_curatorEntities")
        {
        }
        private static Statement_curatorEntities _context;
        public static Statement_curatorEntities GetContext()
        {
            if (_context == null)
                _context = new Statement_curatorEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Curator> Curator { get; set; }
        public virtual DbSet<Health_Card> Health_Card { get; set; }
        public virtual DbSet<Parents> Parents { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Summary_Ledger> Summary_Ledger { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teachers> Teachers { get; set; }
    }
}
