//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Summary_Ledger
    {
        public int Ledger_ID { get; set; }
        public Nullable<int> Student_ID { get; set; }
        public Nullable<int> Teacher_ID { get; set; }
        public string Grade { get; set; }
        public string Semester { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
